# -*- coding: utf-8 -*-
"""HackAIthon_NOSleepClub_resQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukSOhY0Corf-nrYNSTFN_hQeeHElO90c
"""

#HackAIthon
#Missing Person Finder
#resQ: Reuniting Lives, Restoring Hopes!
#Please read the document from page 3 onwards for better understanding
#Thank you!
#The code is incomplete, need to work on it more!

#Backend using FastAPI

from fastapi import FastAPI, UploadFile, File
import requests
import face_recognition
import shutil
import os

app=FastAPI()

#API keys
NEWS_API_KEY=89a7b939536e400ea7bca88634aa8c0c
TWITTER_BEARER_TOKEN="api key"
FACE_RECOGNITION_API="api key"

UPLOAD_DIR="upload image"
os.markeddirs(UPLOAD, exist_ok=True)

#Fetching Missing Person News from NewsAPI
@app.get("/search_news")
def fetch_missing_person_news():
  url =
  response = requests.get(url).json()
  return response.get("articles", [])

#Fetching Social Media posts
@app.get("/search twitter")
def fetch_social_media_posts(query="missing person", max_results=10):
  url =
  headers = {"Authorization": f"Bearer {TWITTER_BEARER_TOKEN}"}
  response = requests.get(url, headers=headers).json()
  return response.get("data", [])

#Convert Address to Coordinates using Google Maps API
@app.get("/geocode")
def get_coordinates(address: str):
  url =
  response = requests.get(url).json()
  if response["status"]=="OK":
    return response["results"][0]["geometry"]["location"]
  return {"error": "Invalid address"}

#Uploading image and Facial Recognition
@app.post("/upload_face")
def upload_and_recognize(file: UploadFile = File(...)):
  file_path = f"{UPLOAD_DIR}/(file.filename)"
  with open(file_path, "wb") as buffer:
    shutil.copyfileobj(file.file,buffer)

    #loading and encoding uploaded image
    image = face_recognition.load_image_file(file_path)
    encodings = face_recognition.face_encodings(image)

    if encodings:
      return {"message": "Image uploaded sucessfully!", "encoding": encodings[0].tolist()}
    return{"error": "No face detected"}